import { supabase } from "./supabase";

// Type definitions
export interface ComplaintCategory {
  name: string;
}

export type ComplaintStatus = "Pending" | "In Progress" | "Resolved" | "Rejected";

export interface Complaint {
  id: string;
  resident_id: string;
  complaint_code: string;
  category: string;
  description: string;
  location?: string;
  image_url?: string;
  status: ComplaintStatus;
  remarks?: string;
  created_at: string;
  updated_at: string;
  // These may be populated from joins
  residentName?: string;
  residentEmail?: string;
}

export interface CreateComplaintData {
  category: string;
  description: string;
  location?: string;
  imageUrl?: string;
}

export interface CreateComplaintResponse {
  success: boolean;
  data?: Complaint;
  message: string;
  error?: string;
}

export interface GetComplaintsResponse {
  success: boolean;
  data?: Complaint[];
  message: string;
  error?: string;
  count?: number;
}

export interface UpdateComplaintResponse {
  success: boolean;
  data?: Complaint;
  message: string;
  error?: string;
}

export interface DeleteComplaintResponse {
  success: boolean;
  message: string;
  error?: string;
}

export interface BanResidentResponse {
  success: boolean;
  message: string;
  error?: string;
}

export interface UnbanResidentResponse {
  success: boolean;
  message: string;
  error?: string;
}

export interface ResidentData {
  id: string;
  full_name: string;
  email: string;
  phone_number?: string;
  address?: string;
  status: string;
  role: string;
  created_at: string;
  updated_at: string;
}

export interface GetResidentsResponse {
  success: boolean;
  data?: ResidentData[];
  message: string;
  error?: string;
  count?: number;
}

export interface ComplaintCounts {
  total: number;
  resolved: number;
}

// Helper function to handle lock timeout errors with retry logic
const isLockTimeoutError = (error: unknown): boolean => {
  if (error instanceof Error) {
    return error.message.includes("Lock") || error.message.includes("lock");
  }
  return false;
};

// Helper function to execute with retry for lock timeouts
const executeWithRetry = async <T,>(
  fn: () => Promise<T>,
  maxAttempts: number = 3
): Promise<T> => {
  let lastError: unknown;

  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error;

      // If it's a lock timeout error and we have retries left, wait and retry
      if (isLockTimeoutError(error) && attempt < maxAttempts - 1) {
        const waitTime = 100 * Math.pow(2, attempt); // Exponential backoff: 100ms, 200ms, 400ms
        await new Promise((resolve) => setTimeout(resolve, waitTime));
        continue;
      }

      // If not a lock error or it's the last attempt, throw
      throw error;
    }
  }

  throw lastError;
};

// Validate complaint data
const validateComplaintData = (
  data: CreateComplaintData
): { isValid: boolean; error?: string } => {
  if (!data.category || !data.category.trim()) {
    return { isValid: false, error: "Category is required" };
  }

  if (!data.description || !data.description.trim()) {
    return { isValid: false, error: "Description is required" };
  }

  if (data.description.trim().length < 20) {
    return {
      isValid: false,
      error: "Description must be at least 20 characters long",
    };
  }

  return { isValid: true };
};

// Create a new complaint
export const createComplaint = async (
  data: CreateComplaintData
): Promise<CreateComplaintResponse> => {
  try {
    // Validate input first
    const validation = validateComplaintData(data);
    if (!validation.isValid) {
      return {
        success: false,
        message: "Validation failed",
        error: validation.error,
      };
    }

    // Get current user with retry logic for lock timeouts
    const { data: { user }, error: userError } = await executeWithRetry(() =>
      supabase.auth.getUser()
    );

    if (userError || !user) {
      return {
        success: false,
        message: "Failed to create complaint",
        error: "You must be logged in to submit a complaint",
      };
    }

    // Create complaint - complaint_code will be auto-generated by trigger
    const { data: complaint, error: insertError } = await supabase
      .from("complaints")
      .insert([
        {
          resident_id: user.id,
          category: data.category.trim(),
          description: data.description.trim(),
          location: data.location?.trim() || null,
          image_url: data.imageUrl || null,
          status: "Pending",
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ])
      .select()
      .single();

    if (insertError) {
      console.error("Insert error:", insertError);
      return {
        success: false,
        message: "Failed to create complaint",
        error: insertError.message || "An error occurred while creating your complaint",
      };
    }

    if (!complaint) {
      return {
        success: false,
        message: "Failed to create complaint",
        error: "Complaint was created but could not be retrieved",
      };
    }

    return {
      success: true,
      data: complaint,
      message: `Complaint ${complaint.complaint_code} submitted successfully!`,
    };
  } catch (error) {
    console.error("Unexpected error creating complaint:", error);
    return {
      success: false,
      message: "Failed to create complaint",
      error: "An unexpected error occurred. Please try again.",
    };
  }
};

// Get complaints for current resident
export const getResidentComplaints = async (
  status?: ComplaintStatus,
  category?: string,
  search?: string,
  residentId?: string
): Promise<GetComplaintsResponse> => {
  try {
    let userId = residentId;

    // Only fetch user if residentId not provided (for backward compatibility)
    if (!userId) {
      const { data: { user }, error: userError } = await executeWithRetry(() =>
        supabase.auth.getUser()
      );

      if (userError || !user) {
        return {
          success: false,
          message: "Failed to fetch complaints",
          error: "You must be logged in",
        };
      }
      userId = user.id;
    }

    // Start with base query
    let query = supabase
      .from("complaints")
      .select("*", { count: "exact" })
      .eq("resident_id", userId)
      .order("created_at", { ascending: false });

    // Apply filters if provided
    if (status) {
      query = query.eq("status", status);
    }

    if (category && category !== "All") {
      query = query.eq("category", category);
    }

    const { data, error, count } = await query;

    if (error) {
      console.error("Fetch error:", error);
      return {
        success: false,
        message: "Failed to fetch complaints",
        error: error.message || "An error occurred while fetching complaints",
      };
    }

    // Apply client-side search if provided
    let complaints = data || [];
    if (search) {
      const searchLower = search.toLowerCase();
      complaints = complaints.filter(
        (c) =>
          c.complaint_code.toLowerCase().includes(searchLower) ||
          c.category.toLowerCase().includes(searchLower) ||
          c.description.toLowerCase().includes(searchLower)
      );
    }

    return {
      success: true,
      data: complaints,
      message: "Complaints fetched successfully",
      count: complaints.length,
    };
  } catch (error) {
    console.error("Unexpected error fetching resident complaints:", error);
    return {
      success: false,
      message: "Failed to fetch complaints",
      error: "An unexpected error occurred. Please try again.",
    };
  }
};

// Get all complaints (for admins)
export const getAllComplaints = async (
  status?: ComplaintStatus,
  category?: string,
  search?: string,
  userRole?: string,
  userId?: string
): Promise<GetComplaintsResponse> => {
  try {
    let adminRole = userRole;
    let adminId = userId;

    // Only fetch user if role/userId not provided (for backward compatibility)
    if (!adminRole || !adminId) {
      const { data: { user }, error: userError } = await executeWithRetry(() =>
        supabase.auth.getUser()
      );

      if (userError || !user) {
        return {
          success: false,
          message: "Failed to fetch complaints",
          error: "You must be logged in",
        };
      }
      adminId = user.id;

      // Verify user is admin - fetch resident record with retry logic
      const { data: resident, error: residentError } = await executeWithRetry(async () =>
        await supabase.from("residents").select("role").eq("id", user.id).single()
      ) as any;

      if (residentError || !resident || resident.role !== "admin") {
        return {
          success: false,
          message: "Access denied",
          error: "Only admins can view all complaints",
        };
      }
      adminRole = resident.role;
    } else if (adminRole !== "admin") {
      return {
        success: false,
        message: "Access denied",
        error: "Only admins can view all complaints",
      };
    }

    // Start with base query
    let query = supabase
      .from("complaints")
      .select(
        `
        *,
        residents:resident_id(full_name, email)
      `,
        { count: "exact" }
      )
      .order("created_at", { ascending: false });

    // Apply filters if provided
    if (status) {
      query = query.eq("status", status);
    }

    if (category && category !== "All") {
      query = query.eq("category", category);
    }

    const { data, error, count } = await query;

    if (error) {
      console.error("Fetch error:", error);
      return {
        success: false,
        message: "Failed to fetch complaints",
        error: error.message || "An error occurred while fetching complaints",
      };
    }

    // Transform data to include resident info
    let complaints: Complaint[] = (data || []).map((c: any) => ({
      ...c,
      residentName: c.residents?.full_name || "Unknown",
      residentEmail: c.residents?.email || "Unknown",
    }));

    // Apply client-side search if provided
    if (search) {
      const searchLower = search.toLowerCase();
      complaints = complaints.filter(
        (c) =>
          c.complaint_code.toLowerCase().includes(searchLower) ||
          (c.residentName || "Unknown").toLowerCase().includes(searchLower) ||
          c.category.toLowerCase().includes(searchLower) ||
          c.description.toLowerCase().includes(searchLower)
      );
    }

    return {
      success: true,
      data: complaints,
      message: "Complaints fetched successfully",
      count: complaints.length,
    };
  } catch (error) {
    console.error("Unexpected error fetching all complaints:", error);
    return {
      success: false,
      message: "Failed to fetch complaints",
      error: "An unexpected error occurred. Please try again.",
    };
  }
};

// Update complaint status and remarks (admin only)
export const updateComplaintStatus = async (
  complaintId: string,
  status: ComplaintStatus,
  remarks?: string
): Promise<UpdateComplaintResponse> => {
  try {
    // Validate input
    if (!complaintId) {
      return {
        success: false,
        message: "Validation failed",
        error: "Complaint ID is required",
      };
    }

    if (!status) {
      return {
        success: false,
        message: "Validation failed",
        error: "Status is required",
      };
    }

    const validStatuses: ComplaintStatus[] = [
      "Pending",
      "In Progress",
      "Resolved",
      "Rejected",
    ];
    if (!validStatuses.includes(status)) {
      return {
        success: false,
        message: "Validation failed",
        error: "Invalid status value",
      };
    }

    // Get current user to verify admin with retry logic for lock timeouts
    const { data: { user }, error: userError } = await executeWithRetry(() =>
      supabase.auth.getUser()
    );

    if (userError || !user) {
      return {
        success: false,
        message: "Failed to update complaint",
        error: "You must be logged in",
      };
    }

    // Verify user is admin with retry logic
    const { data: resident, error: residentError } = await executeWithRetry(async () =>
      await supabase.from("residents").select("role").eq("id", user.id).single()
    ) as any;

    if (residentError || !resident || resident.role !== "admin") {
      return {
        success: false,
        message: "Access denied",
        error: "Only admins can update complaints",
      };
    }

    // Update complaint
    const { data: complaint, error: updateError } = await supabase
      .from("complaints")
      .update({
        status,
        remarks: remarks?.trim() || null,
        updated_at: new Date().toISOString(),
      })
      .eq("id", complaintId)
      .select()
      .single();

    if (updateError) {
      console.error("Update error:", updateError);
      return {
        success: false,
        message: "Failed to update complaint",
        error: updateError.message || "An error occurred while updating the complaint",
      };
    }

    if (!complaint) {
      return {
        success: false,
        message: "Failed to update complaint",
        error: "Complaint not found or could not be updated",
      };
    }

    return {
      success: true,
      data: complaint,
      message: `Complaint ${complaint.complaint_code} updated successfully`,
    };
  } catch (error) {
    console.error("Unexpected error updating complaint:", error);
    return {
      success: false,
      message: "Failed to update complaint",
      error: "An unexpected error occurred. Please try again.",
    };
  }
};

// Search complaints (helper function)
export const searchComplaints = async (
  query: string,
  resident_id?: string
): Promise<GetComplaintsResponse> => {
  try {
    if (!query.trim()) {
      return {
        success: true,
        data: [],
        message: "No search query provided",
      };
    }

    const searchLower = query.toLowerCase();

    if (resident_id) {
      // Search within resident's complaints
      return getResidentComplaints(undefined, undefined, query);
    } else {
      // Search all complaints (admin only)
      return getAllComplaints(undefined, undefined, query);
    }
  } catch (error) {
    console.error("Unexpected error searching complaints:", error);
    return {
      success: false,
      message: "Failed to search complaints",
      error: "An unexpected error occurred. Please try again.",
    };
  }
};

// Delete complaint (admin only)
export const deleteComplaint = async (
  complaintId: string
): Promise<DeleteComplaintResponse> => {
  try {
    // Validate input
    if (!complaintId) {
      return {
        success: false,
        message: "Validation failed",
        error: "Complaint ID is required",
      };
    }

    // Get current user to verify admin with retry logic for lock timeouts
    const { data: { user }, error: userError } = await executeWithRetry(() =>
      supabase.auth.getUser()
    );

    if (userError || !user) {
      return {
        success: false,
        message: "Access denied",
        error: "You must be logged in",
      };
    }

    // Verify user is admin with retry logic
    const { data: resident, error: residentError } = await executeWithRetry(async () =>
      await supabase.from("residents").select("role").eq("id", user.id).single()
    ) as any;

    if (residentError || !resident || resident.role !== "admin") {
      return {
        success: false,
        message: "Access denied",
        error: "Only admins can delete complaints",
      };
    }

    // Get complaint code before deleting (for message)
    const { data: complaint, error: fetchError } = await supabase
      .from("complaints")
      .select("complaint_code")
      .eq("id", complaintId)
      .single();

    if (fetchError || !complaint) {
      console.error("Fetch error:", fetchError);
      return {
        success: false,
        message: "Failed to delete complaint",
        error: "Complaint not found",
      };
    }

    // Delete complaint
    const { error: deleteError } = await supabase
      .from("complaints")
      .delete()
      .eq("id", complaintId);

    if (deleteError) {
      console.error("Delete error:", deleteError);
      return {
        success: false,
        message: "Failed to delete complaint",
        error: deleteError.message || "An error occurred while deleting the complaint",
      };
    }

    return {
      success: true,
      message: `Complaint ${complaint.complaint_code} deleted successfully`,
    };
  } catch (error) {
    console.error("Unexpected error deleting complaint:", error);
    return {
      success: false,
      message: "Failed to delete complaint",
      error: "An unexpected error occurred. Please try again.",
    };
  }
};

// Ban a resident (admin only)
export const banResident = async (
  residentId: string
): Promise<BanResidentResponse> => {
  try {
    // Validate input
    if (!residentId) {
      return {
        success: false,
        message: "Validation failed",
        error: "Resident ID is required",
      };
    }

    // Get current user to verify admin with retry logic for lock timeouts
    const { data: { user }, error: userError } = await executeWithRetry(() =>
      supabase.auth.getUser()
    );

    if (userError || !user) {
      return {
        success: false,
        message: "Access denied",
        error: "You must be logged in",
      };
    }

    // Verify user is admin with retry logic
    const { data: resident, error: residentError } = await executeWithRetry(async () =>
      await supabase.from("residents").select("role").eq("id", user.id).single()
    ) as any;

    if (residentError || !resident || resident.role !== "admin") {
      return {
        success: false,
        message: "Access denied",
        error: "Only admins can ban residents",
      };
    }

    // Get resident details before updating (for message)
    const { data: targetResident, error: fetchError } = await supabase
      .from("residents")
      .select("full_name, status")
      .eq("id", residentId)
      .single();

    if (fetchError || !targetResident) {
      console.error("Fetch error:", fetchError);
      return {
        success: false,
        message: "Failed to ban resident",
        error: "Resident not found",
      };
    }

    // Prevent banning yourself
    if (user.id === residentId) {
      return {
        success: false,
        message: "Failed to ban resident",
        error: "You cannot ban yourself",
      };
    }

    // Check if resident is already banned
    if (targetResident.status === "banned") {
      return {
        success: false,
        message: "Resident already banned",
        error: `${targetResident.full_name} is already banned`,
      };
    }

    // Update resident status to banned
    const { error: updateError } = await supabase
      .from("residents")
      .update({
        status: "banned",
        updated_at: new Date().toISOString(),
      })
      .eq("id", residentId);

    if (updateError) {
      console.error("Update error:", updateError);
      return {
        success: false,
        message: "Failed to ban resident",
        error: updateError.message || "An error occurred while banning the resident",
      };
    }

    return {
      success: true,
      message: `${targetResident.full_name} has been banned successfully`,
    };
  } catch (error) {
    console.error("Unexpected error banning resident:", error);
    return {
      success: false,
      message: "Failed to ban resident",
      error: "An unexpected error occurred. Please try again.",
    };
  }
};

// Unban a resident (admin only)
export const unbanResident = async (
  residentId: string
): Promise<UnbanResidentResponse> => {
  try {
    // Validate input
    if (!residentId) {
      return {
        success: false,
        message: "Validation failed",
        error: "Resident ID is required",
      };
    }

    // Get current user to verify admin with retry logic for lock timeouts
    const { data: { user }, error: userError } = await executeWithRetry(() =>
      supabase.auth.getUser()
    );

    if (userError || !user) {
      return {
        success: false,
        message: "Access denied",
        error: "You must be logged in",
      };
    }

    // Verify user is admin with retry logic
    const { data: resident, error: residentError } = await executeWithRetry(async () =>
      await supabase.from("residents").select("role").eq("id", user.id).single()
    ) as any;

    if (residentError || !resident || resident.role !== "admin") {
      return {
        success: false,
        message: "Access denied",
        error: "Only admins can unban residents",
      };
    }

    // Get resident details before updating (for message)
    const { data: targetResident, error: fetchError } = await supabase
      .from("residents")
      .select("full_name, status")
      .eq("id", residentId)
      .single();

    if (fetchError || !targetResident) {
      console.error("Fetch error:", fetchError);
      return {
        success: false,
        message: "Failed to unban resident",
        error: "Resident not found",
      };
    }

    // Check if resident is actually banned
    if (targetResident.status !== "banned") {
      return {
        success: false,
        message: "Failed to unban resident",
        error: `${targetResident.full_name} is not banned`,
      };
    }

    // Update resident status to active
    const { error: updateError } = await supabase
      .from("residents")
      .update({
        status: "active",
        updated_at: new Date().toISOString(),
      })
      .eq("id", residentId);

    if (updateError) {
      console.error("Update error:", updateError);
      return {
        success: false,
        message: "Failed to unban resident",
        error: updateError.message || "An error occurred while unbanning the resident",
      };
    }

    return {
      success: true,
      message: `${targetResident.full_name} has been unbanned successfully`,
    };
  } catch (error) {
    console.error("Unexpected error unbanning resident:", error);
    return {
      success: false,
      message: "Failed to unban resident",
      error: "An unexpected error occurred. Please try again.",
    };
  }
};

// Get all residents (admin only)
export const getAllResidents = async (
  search?: string
): Promise<GetResidentsResponse> => {
  try {
    // Get current user to verify admin
    const { data: { user }, error: userError } = await executeWithRetry(() =>
      supabase.auth.getUser()
    );

    if (userError || !user) {
      return {
        success: false,
        message: "Failed to fetch residents",
        error: "You must be logged in",
      };
    }

    // Verify user is admin
    const { data: adminResident, error: residentError } = await executeWithRetry(async () =>
      await supabase.from("residents").select("role").eq("id", user.id).single()
    ) as any;

    if (residentError || !adminResident || adminResident.role !== "admin") {
      return {
        success: false,
        message: "Access denied",
        error: "Only admins can view all residents",
      };
    }

    // Fetch all residents (excluding admin role)
    const { data: residents, error: fetchError } = await supabase
      .from("residents")
      .select("*")
      .neq("role", "admin")
      .order("created_at", { ascending: false });

    if (fetchError) {
      console.error("Fetch error:", fetchError);
      return {
        success: false,
        message: "Failed to fetch residents",
        error: fetchError.message || "An error occurred while fetching residents",
      };
    }

    let result = residents || [];

    // Apply search filter if provided
    if (search) {
      const searchLower = search.toLowerCase();
      result = result.filter(
        (r) =>
          r.full_name?.toLowerCase().includes(searchLower) ||
          r.email?.toLowerCase().includes(searchLower)
      );
    }

    return {
      success: true,
      data: result,
      message: "Residents fetched successfully",
      count: result.length,
    };
  } catch (error) {
    console.error("Unexpected error fetching residents:", error);
    return {
      success: false,
      message: "Failed to fetch residents",
      error: "An unexpected error occurred. Please try again.",
    };
  }
};

// ─── Public / Community Complaints ────────────────────────────────────────────
// Returns all complaints visible to any authenticated user (no admin role required).
// Used by the Community Complaints page in the resident portal.
export const getPublicComplaints = async (
  status?: ComplaintStatus,
  category?: string,
  search?: string
): Promise<GetComplaintsResponse> => {
  try {
    // Ensure the user is authenticated
    const { data: { user }, error: userError } = await executeWithRetry(() =>
      supabase.auth.getUser()
    );

    if (userError || !user) {
      return {
        success: false,
        message: "Failed to fetch complaints",
        error: "You must be logged in",
      };
    }

    let query = supabase
      .from("complaints")
      .select(
        `
        *,
        residents:resident_id(full_name)
      `,
        { count: "exact" }
      )
      .order("created_at", { ascending: false });

    if (status) query = query.eq("status", status);
    if (category && category !== "All") query = query.eq("category", category);

    const { data, error, count } = await query;

    if (error) {
      console.error("Public fetch error:", error);
      return {
        success: false,
        message: "Failed to fetch complaints",
        error: error.message || "An error occurred while fetching complaints",
      };
    }

    // Map the joined residents row into the flat residentName field
    let complaints: Complaint[] = (data || []).map((c: any) => ({
      ...c,
      residentName: c.residents?.full_name || "Anonymous",
    }));

    if (search) {
      const q = search.toLowerCase();
      complaints = complaints.filter(
        (c) =>
          c.complaint_code.toLowerCase().includes(q) ||
          c.category.toLowerCase().includes(q) ||
          c.description.toLowerCase().includes(q) ||
          (c.location ?? "").toLowerCase().includes(q) ||
          (c.residentName ?? "").toLowerCase().includes(q)
      );
    }

    return {
      success: true,
      data: complaints,
      message: "Community complaints fetched successfully",
      count: complaints.length,
    };
  } catch (error) {
    console.error("Unexpected error fetching public complaints:", error);
    return {
      success: false,
      message: "Failed to fetch complaints",
      error: "An unexpected error occurred. Please try again.",
    };
  }
};

export const getComplaintCounts = async (): Promise<ComplaintCounts> => {
  try {
    const { data: totalData, count: totalCount, error: totalError } = await supabase
      .from("complaints")
      .select("*", { count: "exact" });

    if (totalError) {
      console.error("Failed to fetch total complaint count:", totalError);
      return { total: 0, resolved: 0 };
    }

    const { data: resolvedData, count: resolvedCount, error: resolvedError } = await supabase
      .from("complaints")
      .select("*", { count: "exact" })
      .eq("status", "Resolved");

    if (resolvedError) {
      console.error("Failed to fetch resolved complaint count:", resolvedError);
      return { total: totalCount ?? totalData?.length ?? 0, resolved: 0 };
    }

    const total = totalCount ?? totalData?.length ?? 0;
    const resolved = resolvedCount ?? resolvedData?.length ?? 0;

    return { total, resolved };
  } catch (error) {
    console.error("Unexpected error fetching complaint counts:", error);
    return { total: 0, resolved: 0 };
  }
};

// ─── User Verification Methods ────────────────────────────────────────────────

export interface PendingUser {
  id: string;
  full_name: string;
  email: string;
  id_type: string;
  id_front_url: string | null;
  id_back_url: string | null;
  created_at: string;
}

export interface UserVerificationResponse {
  success: boolean;
  message: string;
  error?: string;
}

// Get pending user verifications (admin only)
export const getPendingVerifications = async (): Promise<PendingUser[]> => {
  try {
    // Get current user to verify admin
    const { data: { user }, error: userError } = await executeWithRetry(() =>
      supabase.auth.getUser()
    );

    if (userError || !user) {
      throw new Error("You must be logged in");
    }

    // Verify user is admin
    const { data: adminResident, error: residentError } = await executeWithRetry(async () =>
      await supabase.from("residents").select("role").eq("id", user.id).single()
    ) as any;

    if (residentError || !adminResident || adminResident.role !== "admin") {
      throw new Error("Access denied: Only admins can view pending verifications");
    }

    // Fetch pending users
    const { data: pendingUsers, error: fetchError } = await supabase
      .from("residents")
      .select("id, full_name, email, id_type, id_front_url, id_back_url, created_at")
      .eq("account_status", "pending_approval")
      .order("created_at", { ascending: false });

    if (fetchError) {
      console.error("Fetch error:", fetchError);
      throw new Error(fetchError.message || "Failed to fetch pending verifications");
    }

    return pendingUsers || [];
  } catch (error) {
    console.error("Error fetching pending verifications:", error);
    throw error;
  }
};

// Get approved users (admin only)
export const getApprovedUsers = async (): Promise<PendingUser[]> => {
  try {
    // Get current user to verify admin
    const { data: { user }, error: userError } = await executeWithRetry(() =>
      supabase.auth.getUser()
    );

    if (userError || !user) {
      throw new Error("You must be logged in");
    }

    // Verify user is admin
    const { data: adminResident, error: residentError } = await executeWithRetry(async () =>
      await supabase.from("residents").select("role").eq("id", user.id).single()
    ) as any;

    if (residentError || !adminResident || adminResident.role !== "admin") {
      throw new Error("Access denied: Only admins can view approved users");
    }

    // Fetch approved users
    const { data: approvedUsers, error: fetchError } = await supabase
      .from("residents")
      .select("id, full_name, email, id_type, id_front_url, id_back_url, created_at")
      .eq("account_status", "approved")
      .order("approval_date", { ascending: false });

    if (fetchError) {
      console.error("Fetch error:", fetchError);
      throw new Error(fetchError.message || "Failed to fetch approved users");
    }

    return approvedUsers || [];
  } catch (error) {
    console.error("Error fetching approved users:", error);
    throw error;
  }
};

// Get rejected users (admin only)
export const getRejectedUsers = async (): Promise<PendingUser[]> => {
  try {
    // Get current user to verify admin
    const { data: { user }, error: userError } = await executeWithRetry(() =>
      supabase.auth.getUser()
    );

    if (userError || !user) {
      throw new Error("You must be logged in");
    }

    // Verify user is admin
    const { data: adminResident, error: residentError } = await executeWithRetry(async () =>
      await supabase.from("residents").select("role").eq("id", user.id).single()
    ) as any;

    if (residentError || !adminResident || adminResident.role !== "admin") {
      throw new Error("Access denied: Only admins can view rejected users");
    }

    // Fetch rejected users
    const { data: rejectedUsers, error: fetchError } = await supabase
      .from("residents")
      .select("id, full_name, email, id_type, id_front_url, id_back_url, created_at, rejection_reason")
      .eq("account_status", "rejected")
      .order("updated_at", { ascending: false });

    if (fetchError) {
      console.error("Fetch error:", fetchError);
      throw new Error(fetchError.message || "Failed to fetch rejected users");
    }

    return rejectedUsers || [];
  } catch (error) {
    console.error("Error fetching rejected users:", error);
    throw error;
  }
};

// Approve user registration (admin only)
export const approveUser = async (userId: string): Promise<UserVerificationResponse> => {
  try {
    // Validate input
    if (!userId) {
      return {
        success: false,
        message: "Validation failed",
        error: "User ID is required",
      };
    }

    // Get current user to verify admin
    const { data: { user }, error: userError } = await executeWithRetry(() =>
      supabase.auth.getUser()
    );

    if (userError || !user) {
      return {
        success: false,
        message: "Access denied",
        error: "You must be logged in",
      };
    }

    // Verify user is admin
    const { data: adminResident, error: residentError } = await executeWithRetry(async () =>
      await supabase.from("residents").select("role").eq("id", user.id).single()
    ) as any;

    if (residentError || !adminResident || adminResident.role !== "admin") {
      return {
        success: false,
        message: "Access denied",
        error: "Only admins can approve users",
      };
    }

    // Get user details before updating
    const { data: targetUser, error: fetchError } = await supabase
      .from("residents")
      .select("full_name, account_status")
      .eq("id", userId)
      .single();

    if (fetchError || !targetUser) {
      console.error("Fetch error:", fetchError);
      return {
        success: false,
        message: "Failed to approve user",
        error: "User not found",
      };
    }

    // Check if user is already approved
    if (targetUser.account_status === "approved") {
      return {
        success: false,
        message: "User already approved",
        error: `${targetUser.full_name} is already approved`,
      };
    }

    // Update user status to approved
    const { error: updateError } = await supabase
      .from("residents")
      .update({
        account_status: "approved",
        approval_date: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .eq("id", userId);

    if (updateError) {
      console.error("Update error:", updateError);
      return {
        success: false,
        message: "Failed to approve user",
        error: updateError.message || "An error occurred while approving the user",
      };
    }

    return {
      success: true,
      message: `${targetUser.full_name} has been approved successfully`,
    };
  } catch (error) {
    console.error("Unexpected error approving user:", error);
    return {
      success: false,
      message: "Failed to approve user",
      error: "An unexpected error occurred. Please try again.",
    };
  }
};

// Reject user registration (admin only)
export const rejectUser = async (
  userId: string,
  reason: string
): Promise<UserVerificationResponse> => {
  try {
    // Validate input
    if (!userId) {
      return {
        success: false,
        message: "Validation failed",
        error: "User ID is required",
      };
    }

    if (!reason || !reason.trim()) {
      return {
        success: false,
        message: "Validation failed",
        error: "Rejection reason is required",
      };
    }

    // Get current user to verify admin
    const { data: { user }, error: userError } = await executeWithRetry(() =>
      supabase.auth.getUser()
    );

    if (userError || !user) {
      return {
        success: false,
        message: "Access denied",
        error: "You must be logged in",
      };
    }

    // Verify user is admin
    const { data: adminResident, error: residentError } = await executeWithRetry(async () =>
      await supabase.from("residents").select("role").eq("id", user.id).single()
    ) as any;

    if (residentError || !adminResident || adminResident.role !== "admin") {
      return {
        success: false,
        message: "Access denied",
        error: "Only admins can reject users",
      };
    }

    // Get user details before updating
    const { data: targetUser, error: fetchError } = await supabase
      .from("residents")
      .select("full_name, account_status")
      .eq("id", userId)
      .single();

    if (fetchError || !targetUser) {
      console.error("Fetch error:", fetchError);
      return {
        success: false,
        message: "Failed to reject user",
        error: "User not found",
      };
    }

    // Check if user is already rejected
    if (targetUser.account_status === "rejected") {
      return {
        success: false,
        message: "User already rejected",
        error: `${targetUser.full_name} is already rejected`,
      };
    }

    // Update user status to rejected
    const { error: updateError } = await supabase
      .from("residents")
      .update({
        account_status: "rejected",
        rejection_reason: reason.trim(),
        updated_at: new Date().toISOString(),
      })
      .eq("id", userId);

    if (updateError) {
      console.error("Update error:", updateError);
      return {
        success: false,
        message: "Failed to reject user",
        error: updateError.message || "An error occurred while rejecting the user",
      };
    }

    return {
      success: true,
      message: `${targetUser.full_name} has been rejected successfully`,
    };
  } catch (error) {
    console.error("Unexpected error rejecting user:", error);
    return {
      success: false,
      message: "Failed to reject user",
      error: "An unexpected error occurred. Please try again.",
    };
  }
};

